/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * BacControl.lh
 */
export class BacControlBase extends Laya.Box {
    public playerPairBtn!: Laya.Button;
    public playerBtn!: Laya.Button;
    public tieBtn!: Laya.Button;
    public bankerBtn!: Laya.Button;
    public bankerPairBtn!: Laya.Button;
    public playerBonusBtn!: Laya.Button;
    public bankerBonusBtn!: Laya.Button;
    public super6Btn!: Laya.Button;
    public playerNaturalBtn!: Laya.Button;
    public bankerNaturalBtn!: Laya.Button;
    public clearBtn!: Laya.Button;
}

