/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * dgtgRoadmap.lh
 */
export class BacRoadmapRenderBase extends Laya.Box {
    public bead_plate_road_box!: Laya.Box;
    public bead_plate_road_panel!: Laya.Panel;
    public bead_plate_road_sprite!: Laya.Sprite;
    public big_road_box!: Laya.Box;
    public big_road_panel!: Laya.Panel;
    public big_road_sprite!: Laya.Sprite;
    public big_eye_road_box!: Laya.Box;
    public big_eye_road_panel!: Laya.Panel;
    public big_eye_road_sprite!: Laya.Sprite;
    public small_road_box!: Laya.Box;
    public small_road_panel!: Laya.Panel;
    public small_road_sprite!: Laya.Sprite;
    public cockroach_road_box!: Laya.Box;
    public cockroach_road_panel!: Laya.Panel;
    public cockroach_road_sprite!: Laya.Sprite;
    public wenlu_Xian!: Laya.Box;
    public wenlu_Zhuang!: Laya.Box;
    public switchBtn!: Laya.Button;
}

