/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * BacRoadmapV2.lh
 */
export class BacRoadmapV2Base extends Laya.Box {
    public bead_plate_road_box!: Laya.Box;
    public bead_plate_road_panel!: Laya.Panel;
    public bead_plate_road_sprite!: Laya.Sprite;
    public big_road_box!: Laya.Box;
    public big_road_panel!: Laya.Panel;
    public big_road_sprite!: Laya.Sprite;
    public three_road_box!: Laya.Box;
    public big_eye_road_box!: Laya.Box;
    public big_eye_road_panel!: Laya.Panel;
    public big_eye_road_sprite!: Laya.Sprite;
    public small_road_box!: Laya.Box;
    public small_road_panel!: Laya.Panel;
    public small_road_sprite!: Laya.Sprite;
    public cockroach_road_box!: Laya.Box;
    public cockroach_road_panel!: Laya.Panel;
    public cockroach_road_sprite!: Laya.Sprite;
    public wenlu_Zhuang!: Laya.Box;
    public wenlu_Xian!: Laya.Box;
    public switchBtn!: Laya.Button;
    public resultBox!: Laya.Box;
    public resultLbl!: Laya.Label;
    public playerPairBtn!: Laya.Button;
    public playerBtn!: Laya.Button;
    public tieBtn!: Laya.Button;
    public bankerBtn!: Laya.Button;
    public bankerPairBtn!: Laya.Button;
    public playerBonusBtn!: Laya.Button;
    public super6Btn!: Laya.Button;
    public bankerBonusBtn!: Laya.Button;
    public playerNaturalBtn!: Laya.Button;
    public bankerNaturalBtn!: Laya.Button;
    public smallBtn!: Laya.Button;
    public bigBtn!: Laya.Button;
    public cancelBtn!: Laya.Button;
    public confirmBtn!: Laya.Button;
    public clearBtn!: Laya.Button;
}

