/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * BacOpencard.lh
 */
export class BacOpenCardBase extends Laya.Sprite {
    public firstBox!: Laya.Box;
    public firstNameLbl!: Laya.Label;
    public firstGoalLbl!: Laya.Label;
    public card1!: Laya.Sprite;
    public card3!: Laya.Sprite;
    public card5!: Laya.Sprite;
    public secondNameLbl!: Laya.Label;
    public secondGoalLbl!: Laya.Label;
    public card2!: Laya.Sprite;
    public card4!: Laya.Sprite;
    public card6!: Laya.Sprite;
}

